global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/health.rules.yml

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
